name: Generate Snake

on:
  schedule:
    - cron: "0 21 * * *"  # Türkiye saatiyle 00:00'da çalışır
# Her gün gece 00:00'da çalışır
  workflow_dispatch:      # Manuel çalıştırma

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake contribution grid
        uses: Platane/snk@v3
        with:
          github_user_name: rabiacevikk
          outputs: |
            dist/github-contribution-grid-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push generated snake
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generated snake contribution grid"
          git push
